# Generated by Django 6.0.1 on 2026-01-20 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_br', models.CharField(max_length=25, unique=True, verbose_name='Matrícula BR')),
                ('matricula_ch', models.CharField(blank=True, max_length=25, null=True, verbose_name='Matrícula CH')),
                ('data_entrega', models.DateField(verbose_name='Data de Entrega')),
                ('data_chegada_br', models.DateField(blank=True, null=True, verbose_name='Data de Chegada BR')),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('tipo', models.CharField(choices=[('DOBRADEIRA', 'Dobradeira'), ('LASER', 'Laser')], max_length=15, verbose_name='Tipo de Máquina')),
            ],
        ),
        migrations.CreateModel(
            name='Apontamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ade_nr12', models.BooleanField(default=False, verbose_name='Adequação NR-12')),
                ('vistoria_final', models.BooleanField(default=False, verbose_name='Vistoria Final')),
                ('dob_start_eletrico', models.BooleanField(default=False, verbose_name='Start Elétrico')),
                ('dob_regulagem', models.BooleanField(default=False, verbose_name='Regulagem')),
                ('dob_teste_dobra', models.BooleanField(default=False, verbose_name='Teste de Dobra')),
                ('las_nivelamento', models.BooleanField(default=False, verbose_name='Nivelamento')),
                ('las_montagem_cabecote', models.BooleanField(default=False, verbose_name='Montagem Estrutura Cabeçote')),
                ('las_posicionamento_perif', models.BooleanField(default=False, verbose_name='Posicionamento Periféricos')),
                ('las_passagem_fibra', models.BooleanField(default=False, verbose_name='Passagem Fibra Óptica')),
                ('las_montagem_cab_elet', models.BooleanField(default=False, verbose_name='Montagem Cabeçote (Elétrica)')),
                ('las_alimentacao', models.BooleanField(default=False, verbose_name='Alimentação da Máquina')),
                ('las_alin_cabecote', models.BooleanField(default=False, verbose_name='Alinhamento Cabeçote')),
                ('las_alin_bico', models.BooleanField(default=False, verbose_name='Alinhamento Bico')),
                ('las_testes_corte', models.BooleanField(default=False, verbose_name='Testes de Corte')),
                ('maquina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apontamento', to='dash.maquina')),
            ],
        ),
    ]
