# Generated by Django 6.0.1 on 2026-01-26 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='exibir_no_dashboard',
            field=models.BooleanField(default=True, verbose_name='Exibir na TV?'),
        ),
        migrations.AlterField(
            model_name='apontamento',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamento', to='dash.maquina'),
        ),
    ]
