# Generated by Django 6.0.1 on 2026-04-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_maquina_exibir_no_dashboard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apontamento',
            name='ade_nr12',
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='dob_regulagem',
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='dob_start_eletrico',
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='dob_teste_dobra',
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='las_alimentacao',
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='las_alin_bico',
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='las_alin_cabecote',
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='las_montagem_cab_elet',
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='las_montagem_cabecote',
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='las_nivelamento',
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='las_passagem_fibra',
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='las_posicionamento_perif',
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='las_testes_corte',
        ),
        migrations.RemoveField(
            model_name='apontamento',
            name='vistoria_final',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='data_entrega',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='matricula_ch',
        ),
        migrations.AddField(
            model_name='apontamento',
            name='carregamento',
            field=models.BooleanField(default=False, verbose_name='Carregamento realizado'),
        ),
        migrations.AddField(
            model_name='apontamento',
            name='data_chegada_br',
            field=models.BooleanField(default=False, verbose_name='Entregue na fábrica'),
        ),
        migrations.AddField(
            model_name='apontamento',
            name='data_embarque',
            field=models.BooleanField(default=False, verbose_name='Embarque realizado'),
        ),
        migrations.AddField(
            model_name='apontamento',
            name='data_entrega_ch',
            field=models.BooleanField(default=False, verbose_name='Entrega China realizada'),
        ),
        migrations.AddField(
            model_name='apontamento',
            name='testes',
            field=models.BooleanField(default=False, verbose_name='Testes concluídos'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='data_embarque',
            field=models.DateField(default=None, verbose_name='Data de Embarque CH'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='data_entrega_ch',
            field=models.DateField(default=None, verbose_name='Data de Entrega Estimada CH'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='data_entrega_cliente',
            field=models.DateField(default=None, verbose_name='Data de Entrega Cliente'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='modelo_maq',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Modelo da Máquina'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='data_chegada_br',
            field=models.DateField(default=None, verbose_name='Data de Chegada BR'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='matricula_br',
            field=models.CharField(max_length=25, unique=True, verbose_name='Matrícula GDB'),
        ),
    ]
