# Generated by Django 6.0.1 on 2026-04-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_remove_apontamento_ade_nr12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='ordem_compra',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Ordem de Compra'),
        ),
    ]
